namespace Core.Models;

public sealed record ExerciseDefinition(
    string Id,
    string Name,
    string Category,
    string MuscleGroup,
    bool Barbell,
    params string[] Aliases);

public static class ExerciseCatalog
{
    // Generated from the frontend exercise list (@/data/exercises.ts) — keep the
    // two in sync. Aliases are intentionally omitted here: matching now relies on
    // the model's semantic understanding of the (English, descriptive) IDs plus a
    // small Polish-shorthand cheat sheet in the DeepSeek system prompt, rather than
    // a hand-maintained alias table per exercise.
    public static readonly IReadOnlyList<ExerciseDefinition> All =
    [
        new("barbell-bench-press", "Barbell Bench Press", "Strength", "Chest", true),
        new("incline-barbell-bench-press", "Incline Barbell Bench Press", "Strength", "Chest", true),
        new("decline-barbell-bench-press", "Decline Barbell Bench Press", "Strength", "Chest", true),
        new("close-grip-bench-press", "Close-Grip Bench Press", "Strength", "Chest", true),
        new("dumbbell-bench-press", "Dumbbell Bench Press", "Strength", "Chest", false),
        new("incline-dumbbell-press", "Incline Dumbbell Press", "Strength", "Chest", false),
        new("decline-dumbbell-press", "Decline Dumbbell Press", "Strength", "Chest", false),
        new("dumbbell-floor-press", "Dumbbell Floor Press", "Strength", "Chest", false),
        new("chest-fly", "Chest Fly", "Strength", "Chest", false),
        new("dumbbell-fly", "Dumbbell Fly", "Strength", "Chest", false),
        new("incline-dumbbell-fly", "Incline Dumbbell Fly", "Strength", "Chest", false),
        new("cable-crossover", "Cable Crossover", "Strength", "Chest", false),
        new("cable-chest-fly", "Cable Chest Fly", "Strength", "Chest", false),
        new("pec-deck", "Pec Deck", "Strength", "Chest", false),
        new("push-up", "Push-Up", "Strength", "Chest", false),
        new("incline-push-up", "Incline Push-Up", "Strength", "Chest", false),
        new("decline-push-up", "Decline Push-Up", "Strength", "Chest", false),
        new("diamond-push-up", "Diamond Push-Up", "Strength", "Chest", false),
        new("dip", "Dip", "Strength", "Chest", false),
        new("assisted-dip", "Assisted Dip", "Strength", "Chest", false),
        new("barbell-deadlift", "Barbell Deadlift", "Strength", "Back", true),
        new("sumo-deadlift", "Sumo Deadlift", "Strength", "Back", true),
        new("romanian-deadlift", "Romanian Deadlift", "Strength", "Hamstrings", true),
        new("stiff-leg-deadlift", "Stiff-Leg Deadlift", "Strength", "Hamstrings", true),
        new("rack-pull", "Rack Pull", "Strength", "Back", true),
        new("barbell-row", "Barbell Row", "Strength", "Back", true),
        new("pendlay-row", "Pendlay Row", "Strength", "Back", true),
        new("t-bar-row", "T-Bar Row", "Strength", "Back", true),
        new("dumbbell-row", "Dumbbell Row", "Strength", "Back", false),
        new("chest-supported-dumbbell-row", "Chest-Supported Dumbbell Row", "Strength", "Back", false),
        new("seated-cable-row", "Seated Cable Row", "Strength", "Back", false),
        new("single-arm-cable-row", "Single-Arm Cable Row", "Strength", "Back", false),
        new("lat-pulldown", "Lat Pulldown", "Strength", "Back", false),
        new("close-grip-lat-pulldown", "Close-Grip Lat Pulldown", "Strength", "Back", false),
        new("wide-grip-lat-pulldown", "Wide-Grip Lat Pulldown", "Strength", "Back", false),
        new("pull-up", "Pull-Up", "Strength", "Back", false),
        new("chin-up", "Chin-Up", "Strength", "Back", false),
        new("assisted-pull-up", "Assisted Pull-Up", "Strength", "Back", false),
        new("neutral-grip-pull-up", "Neutral-Grip Pull-Up", "Strength", "Back", false),
        new("straight-arm-pulldown", "Straight-Arm Pulldown", "Strength", "Back", false),
        new("machine-row", "Machine Row", "Strength", "Back", false),
        new("overhead-press", "Overhead Press", "Strength", "Shoulders", true),
        new("seated-barbell-overhead-press", "Seated Barbell Overhead Press", "Strength", "Shoulders", true),
        new("dumbbell-shoulder-press", "Dumbbell Shoulder Press", "Strength", "Shoulders", false),
        new("arnold-press", "Arnold Press", "Strength", "Shoulders", false),
        new("machine-shoulder-press", "Machine Shoulder Press", "Strength", "Shoulders", false),
        new("dumbbell-lateral-raise", "Dumbbell Lateral Raise", "Strength", "Shoulders", false),
        new("cable-lateral-raise", "Cable Lateral Raise", "Strength", "Shoulders", false),
        new("machine-lateral-raise", "Machine Lateral Raise", "Strength", "Shoulders", false),
        new("front-raise", "Front Raise", "Strength", "Shoulders", false),
        new("dumbbell-front-raise", "Dumbbell Front Raise", "Strength", "Shoulders", false),
        new("rear-delt-fly", "Rear Delt Fly", "Strength", "Shoulders", false),
        new("reverse-pec-deck", "Reverse Pec Deck", "Strength", "Shoulders", false),
        new("face-pull", "Face Pull", "Strength", "Shoulders", false),
        new("upright-row", "Upright Row", "Strength", "Shoulders", true),
        new("barbell-curl", "Barbell Curl", "Strength", "Biceps", true),
        new("ez-bar-curl", "EZ-Bar Curl", "Strength", "Biceps", true),
        new("dumbbell-curl", "Dumbbell Curl", "Strength", "Biceps", false),
        new("alternating-dumbbell-curl", "Alternating Dumbbell Curl", "Strength", "Biceps", false),
        new("hammer-curl", "Hammer Curl", "Strength", "Biceps", false),
        new("cross-body-hammer-curl", "Cross-Body Hammer Curl", "Strength", "Biceps", false),
        new("incline-dumbbell-curl", "Incline Dumbbell Curl", "Strength", "Biceps", false),
        new("preacher-curl", "Preacher Curl", "Strength", "Biceps", false),
        new("preacher-barbell-curl", "Preacher Barbell Curl", "Strength", "Biceps", true),
        new("cable-curl", "Cable Curl", "Strength", "Biceps", false),
        new("concentration-curl", "Concentration Curl", "Strength", "Biceps", false),
        new("triceps-skull-crusher", "Skull Crusher", "Strength", "Triceps", true),
        new("lying-triceps-extension", "Lying Triceps Extension", "Strength", "Triceps", true),
        new("triceps-extension", "Triceps Extension", "Strength", "Triceps", false),
        new("cable-triceps-pushdown", "Cable Triceps Pushdown", "Strength", "Triceps", false),
        new("rope-triceps-pushdown", "Rope Triceps Pushdown", "Strength", "Triceps", false),
        new("overhead-triceps-extension", "Overhead Triceps Extension", "Strength", "Triceps", false),
        new("cable-overhead-triceps-extension", "Cable Overhead Triceps Extension", "Strength", "Triceps", false),
        new("dumbbell-overhead-triceps-extension", "Dumbbell Overhead Triceps Extension", "Strength", "Triceps", false),
        new("triceps-kickback", "Triceps Kickback", "Strength", "Triceps", false),
        new("bench-dip", "Bench Dip", "Strength", "Triceps", false),
        new("barbell-squat", "Barbell Squat", "Strength", "Legs", true),
        new("front-squat", "Front Squat", "Strength", "Legs", true),
        new("hack-squat", "Hack Squat", "Strength", "Legs", false),
        new("leg-press", "Leg Press", "Strength", "Legs", false),
        new("single-leg-press", "Single-Leg Press", "Strength", "Legs", false),
        new("leg-extension", "Leg Extension", "Strength", "Quadriceps", false),
        new("bulgarian-split-squat", "Bulgarian Split Squat", "Strength", "Legs", false),
        new("walking-lunge", "Walking Lunge", "Strength", "Legs", false),
        new("reverse-lunge", "Reverse Lunge", "Strength", "Legs", false),
        new("forward-lunge", "Forward Lunge", "Strength", "Legs", false),
        new("dumbbell-lunge", "Dumbbell Lunge", "Strength", "Legs", false),
        new("step-up", "Step-Up", "Strength", "Legs", false),
        new("goblet-squat", "Goblet Squat", "Strength", "Legs", false),
        new("bodyweight-squat", "Bodyweight Squat", "Strength", "Legs", false),
        new("sumo-squat", "Sumo Squat", "Strength", "Legs", false),
        new("lying-leg-curl", "Lying Leg Curl", "Strength", "Hamstrings", false),
        new("seated-leg-curl", "Seated Leg Curl", "Strength", "Hamstrings", false),
        new("standing-leg-curl", "Standing Leg Curl", "Strength", "Hamstrings", false),
        new("barbell-hip-thrust", "Barbell Hip Thrust", "Strength", "Glutes", true),
        new("glute-bridge", "Glute Bridge", "Strength", "Glutes", false),
        new("single-leg-glute-bridge", "Single-Leg Glute Bridge", "Strength", "Glutes", false),
        new("cable-kickback", "Cable Kickback", "Strength", "Glutes", false),
        new("glute-kickback-machine", "Glute Kickback Machine", "Strength", "Glutes", false),
        new("cable-pull-through", "Cable Pull-Through", "Strength", "Glutes", false),
        new("good-morning", "Good Morning", "Strength", "Hamstrings", true),
        new("calf-raise", "Calf Raise", "Strength", "Calves", false),
        new("standing-calf-raise", "Standing Calf Raise", "Strength", "Calves", false),
        new("seated-calf-raise", "Seated Calf Raise", "Strength", "Calves", false),
        new("leg-press-calf-raise", "Leg Press Calf Raise", "Strength", "Calves", false),
        new("crunch", "Crunch", "Strength", "Abs", false),
        new("sit-up", "Sit-Up", "Strength", "Abs", false),
        new("weighted-sit-up", "Weighted Sit-Up", "Strength", "Abs", false),
        new("cable-crunch", "Cable Crunch", "Strength", "Abs", false),
        new("reverse-crunch", "Reverse Crunch", "Strength", "Abs", false),
        new("leg-raise", "Leg Raise", "Strength", "Abs", false),
        new("hanging-leg-raise", "Hanging Leg Raise", "Strength", "Abs", false),
        new("hanging-knee-raise", "Hanging Knee Raise", "Strength", "Abs", false),
        new("ab-wheel-rollout", "Ab Wheel Rollout", "Strength", "Abs", false),
        new("plank", "Plank", "Strength", "Core", false),
        new("side-plank", "Side Plank", "Strength", "Core", false),
        new("russian-twist", "Russian Twist", "Strength", "Abs", false),
        new("bicycle-crunch", "Bicycle Crunch", "Strength", "Abs", false),
        new("dead-bug", "Dead Bug", "Strength", "Core", false),
        new("bird-dog", "Bird Dog", "Strength", "Core", false),
        new("farmer-walk", "Farmer Walk", "Strength", "Full Body", false),
        new("farmers-carry", "Farmer's Carry", "Strength", "Full Body", false),
        new("suitcase-carry", "Suitcase Carry", "Strength", "Full Body", false),
        new("kettlebell-swing", "Kettlebell Swing", "Strength", "Full Body", false),
        new("kettlebell-clean", "Kettlebell Clean", "Strength", "Full Body", false),
        new("kettlebell-snatch", "Kettlebell Snatch", "Strength", "Full Body", false),
        new("turkish-get-up", "Turkish Get-Up", "Strength", "Full Body", false),
        new("burpee", "Burpee", "Strength", "Full Body", false),
        new("mountain-climber", "Mountain Climber", "Strength", "Full Body", false),
        new("battle-rope", "Battle Rope", "Strength", "Full Body", false),
        new("sled-push", "Sled Push", "Strength", "Full Body", false),
        new("sled-pull", "Sled Pull", "Strength", "Full Body", false),
        new("treadmill-running", "Treadmill Running", "Cardio", "Cardio", false),
        new("treadmill-walking", "Treadmill Walking", "Cardio", "Cardio", false),
        new("incline-treadmill-walking", "Incline Treadmill Walking", "Cardio", "Cardio", false),
        new("outdoor-running", "Outdoor Running", "Cardio", "Cardio", false),
        new("outdoor-walking", "Outdoor Walking", "Cardio", "Cardio", false),
        new("cycling", "Cycling", "Cardio", "Cardio", false),
        new("stationary-bike", "Stationary Bike", "Cardio", "Cardio", false),
        new("spin-bike", "Spin Bike", "Cardio", "Cardio", false),
        new("stair-climber", "Stair Climber", "Cardio", "Cardio", false),
        new("elliptical", "Elliptical", "Cardio", "Cardio", false),
        new("rowing-machine", "Rowing Machine", "Cardio", "Cardio", false),
        new("jump-rope", "Jump Rope", "Cardio", "Cardio", false),
        new("jumping-jacks", "Jumping Jacks", "Cardio", "Cardio", false),
        new("high-knees", "High Knees", "Cardio", "Cardio", false),
        new("power-clean", "Power Clean", "Strength", "Full Body", true),
        new("clean-and-jerk", "Clean and Jerk", "Strength", "Full Body", true),
        new("barbell-snatch", "Barbell Snatch", "Strength", "Full Body", true),
        new("hang-clean", "Hang Clean", "Strength", "Full Body", true),
        new("push-press", "Push Press", "Strength", "Shoulders", true),
        new("push-jerk", "Push Jerk", "Strength", "Full Body", true),
        new("dynamic-warmup", "Dynamic Warm-Up", "Cardio", "Warm-up", false),
        new("jumping-jack-warmup", "Jumping Jack Warm-Up", "Cardio", "Warm-up", false),
        new("arm-circles", "Arm Circles", "Cardio", "Shoulders", false),
        new("hip-circles", "Hip Circles", "Cardio", "Hips", false),
        new("bodyweight-good-morning", "Bodyweight Good Morning", "Strength", "Hamstrings", false),
        new("worlds-greatest-stretch", "World's Greatest Stretch", "Strength", "Full Body", false),
        new("chest-press", "Chest Press", "Strength", "Chest", false),
        new("good-girl", "Good Girl", "Strength", "Glutes", false),
        new("bad-girl", "Bad Girl", "Strength", "Glutes", false),
    ];
}